services:
  post_backend:
    build: .
    command: uvicorn main:app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env

  dramatiq_worker:
    build: .
    command: dramatiq tasks
    volumes:
      - .:/app
    env_file:
      - .env
