services:
  post_backend:
    build: .
    command: uvicorn main:app --reload
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env

  dramatiq_worker:
    build: .
    command: dramatiq taks
    volumes:
      - .:/app
    env_file:
      - .env
