services:
  fastapi:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A celery_app.celery beat --loglevel=info --scheduler redbeat.RedBeatScheduler
    volumes:
      - .:/app
    env_file:
      - .env
